[package]
name = "ecdsa"
version = "0.1.0"
edition = "2024_07"

[executable]

[profile.proving]
inherits = "release"

[profile.proving.cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.9.0"
garaga = { git = "https://github.com/m-kus/garaga", rev = "3c64b14bc60c532df427f765c7177266a4b50991" }
